# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/s2/Projects-CUDA/iceMPM_2d_M

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/s2/Projects-CUDA/iceMPM_2d_M

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/s2/Projects-CUDA/iceMPM_2d_M/CMakeFiles /home/s2/Projects-CUDA/iceMPM_2d_M//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/s2/Projects-CUDA/iceMPM_2d_M/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cplate

# Build rule for target.
cplate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cplate
.PHONY : cplate

# fast build rule for target.
cplate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/build
.PHONY : cplate/fast

#=============================================================================
# Target rules for targets named preparer_cli

# Build rule for target.
preparer_cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preparer_cli
.PHONY : preparer_cli

# fast build rule for target.
preparer_cli/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/build
.PHONY : preparer_cli/fast

#=============================================================================
# Target rules for targets named verify_sort

# Build rule for target.
verify_sort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 verify_sort
.PHONY : verify_sort

# fast build rule for target.
verify_sort/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_sort.dir/build.make CMakeFiles/verify_sort.dir/build
.PHONY : verify_sort/fast

_utilities/main_verify_sort.o: _utilities/main_verify_sort.cpp.o
.PHONY : _utilities/main_verify_sort.o

# target to build an object file
_utilities/main_verify_sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_sort.dir/build.make CMakeFiles/verify_sort.dir/_utilities/main_verify_sort.cpp.o
.PHONY : _utilities/main_verify_sort.cpp.o

_utilities/main_verify_sort.i: _utilities/main_verify_sort.cpp.i
.PHONY : _utilities/main_verify_sort.i

# target to preprocess a source file
_utilities/main_verify_sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_sort.dir/build.make CMakeFiles/verify_sort.dir/_utilities/main_verify_sort.cpp.i
.PHONY : _utilities/main_verify_sort.cpp.i

_utilities/main_verify_sort.s: _utilities/main_verify_sort.cpp.s
.PHONY : _utilities/main_verify_sort.s

# target to generate assembly for a file
_utilities/main_verify_sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_sort.dir/build.make CMakeFiles/verify_sort.dir/_utilities/main_verify_sort.cpp.s
.PHONY : _utilities/main_verify_sort.cpp.s

cli/main.o: cli/main.cpp.o
.PHONY : cli/main.o

# target to build an object file
cli/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/cli/main.cpp.o
.PHONY : cli/main.cpp.o

cli/main.i: cli/main.cpp.i
.PHONY : cli/main.i

# target to preprocess a source file
cli/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/cli/main.cpp.i
.PHONY : cli/main.cpp.i

cli/main.s: cli/main.cpp.s
.PHONY : cli/main.s

# target to generate assembly for a file
cli/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/cli/main.cpp.s
.PHONY : cli/main.cpp.s

gui/colormap.o: gui/colormap.cpp.o
.PHONY : gui/colormap.o

# target to build an object file
gui/colormap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/gui/colormap.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/gui/colormap.cpp.o
.PHONY : gui/colormap.cpp.o

gui/colormap.i: gui/colormap.cpp.i
.PHONY : gui/colormap.i

# target to preprocess a source file
gui/colormap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/gui/colormap.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/gui/colormap.cpp.i
.PHONY : gui/colormap.cpp.i

gui/colormap.s: gui/colormap.cpp.s
.PHONY : gui/colormap.s

# target to generate assembly for a file
gui/colormap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/gui/colormap.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/gui/colormap.cpp.s
.PHONY : gui/colormap.cpp.s

preparer/cli/cli_preparer_main.o: preparer/cli/cli_preparer_main.cpp.o
.PHONY : preparer/cli/cli_preparer_main.o

# target to build an object file
preparer/cli/cli_preparer_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/preparer/cli/cli_preparer_main.cpp.o
.PHONY : preparer/cli/cli_preparer_main.cpp.o

preparer/cli/cli_preparer_main.i: preparer/cli/cli_preparer_main.cpp.i
.PHONY : preparer/cli/cli_preparer_main.i

# target to preprocess a source file
preparer/cli/cli_preparer_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/preparer/cli/cli_preparer_main.cpp.i
.PHONY : preparer/cli/cli_preparer_main.cpp.i

preparer/cli/cli_preparer_main.s: preparer/cli/cli_preparer_main.cpp.s
.PHONY : preparer/cli/cli_preparer_main.s

# target to generate assembly for a file
preparer/cli/cli_preparer_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/preparer/cli/cli_preparer_main.cpp.s
.PHONY : preparer/cli/cli_preparer_main.cpp.s

preparer/data_preparer.o: preparer/data_preparer.cpp.o
.PHONY : preparer/data_preparer.o

# target to build an object file
preparer/data_preparer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/preparer/data_preparer.cpp.o
.PHONY : preparer/data_preparer.cpp.o

preparer/data_preparer.i: preparer/data_preparer.cpp.i
.PHONY : preparer/data_preparer.i

# target to preprocess a source file
preparer/data_preparer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/preparer/data_preparer.cpp.i
.PHONY : preparer/data_preparer.cpp.i

preparer/data_preparer.s: preparer/data_preparer.cpp.s
.PHONY : preparer/data_preparer.s

# target to generate assembly for a file
preparer/data_preparer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/preparer/data_preparer.cpp.s
.PHONY : preparer/data_preparer.cpp.s

preparer/parameterparser.o: preparer/parameterparser.cpp.o
.PHONY : preparer/parameterparser.o

# target to build an object file
preparer/parameterparser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/preparer/parameterparser.cpp.o
.PHONY : preparer/parameterparser.cpp.o

preparer/parameterparser.i: preparer/parameterparser.cpp.i
.PHONY : preparer/parameterparser.i

# target to preprocess a source file
preparer/parameterparser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/preparer/parameterparser.cpp.i
.PHONY : preparer/parameterparser.cpp.i

preparer/parameterparser.s: preparer/parameterparser.cpp.s
.PHONY : preparer/parameterparser.s

# target to generate assembly for a file
preparer/parameterparser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/preparer/parameterparser.cpp.s
.PHONY : preparer/parameterparser.cpp.s

simulation/data_manager/host_side_data.o: simulation/data_manager/host_side_data.cpp.o
.PHONY : simulation/data_manager/host_side_data.o

# target to build an object file
simulation/data_manager/host_side_data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/data_manager/host_side_data.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/simulation/data_manager/host_side_data.cpp.o
.PHONY : simulation/data_manager/host_side_data.cpp.o

simulation/data_manager/host_side_data.i: simulation/data_manager/host_side_data.cpp.i
.PHONY : simulation/data_manager/host_side_data.i

# target to preprocess a source file
simulation/data_manager/host_side_data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/data_manager/host_side_data.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/simulation/data_manager/host_side_data.cpp.i
.PHONY : simulation/data_manager/host_side_data.cpp.i

simulation/data_manager/host_side_data.s: simulation/data_manager/host_side_data.cpp.s
.PHONY : simulation/data_manager/host_side_data.s

# target to generate assembly for a file
simulation/data_manager/host_side_data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/data_manager/host_side_data.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/simulation/data_manager/host_side_data.cpp.s
.PHONY : simulation/data_manager/host_side_data.cpp.s

simulation/data_manager/windandcurrentinterpolator.o: simulation/data_manager/windandcurrentinterpolator.cpp.o
.PHONY : simulation/data_manager/windandcurrentinterpolator.o

# target to build an object file
simulation/data_manager/windandcurrentinterpolator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/data_manager/windandcurrentinterpolator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/simulation/data_manager/windandcurrentinterpolator.cpp.o
.PHONY : simulation/data_manager/windandcurrentinterpolator.cpp.o

simulation/data_manager/windandcurrentinterpolator.i: simulation/data_manager/windandcurrentinterpolator.cpp.i
.PHONY : simulation/data_manager/windandcurrentinterpolator.i

# target to preprocess a source file
simulation/data_manager/windandcurrentinterpolator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/data_manager/windandcurrentinterpolator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/simulation/data_manager/windandcurrentinterpolator.cpp.i
.PHONY : simulation/data_manager/windandcurrentinterpolator.cpp.i

simulation/data_manager/windandcurrentinterpolator.s: simulation/data_manager/windandcurrentinterpolator.cpp.s
.PHONY : simulation/data_manager/windandcurrentinterpolator.s

# target to generate assembly for a file
simulation/data_manager/windandcurrentinterpolator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/data_manager/windandcurrentinterpolator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/simulation/data_manager/windandcurrentinterpolator.cpp.s
.PHONY : simulation/data_manager/windandcurrentinterpolator.cpp.s

simulation/gpu_implementation5.o: simulation/gpu_implementation5.cpp.o
.PHONY : simulation/gpu_implementation5.o

# target to build an object file
simulation/gpu_implementation5.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/gpu_implementation5.cpp.o
.PHONY : simulation/gpu_implementation5.cpp.o

simulation/gpu_implementation5.i: simulation/gpu_implementation5.cpp.i
.PHONY : simulation/gpu_implementation5.i

# target to preprocess a source file
simulation/gpu_implementation5.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/gpu_implementation5.cpp.i
.PHONY : simulation/gpu_implementation5.cpp.i

simulation/gpu_implementation5.s: simulation/gpu_implementation5.cpp.s
.PHONY : simulation/gpu_implementation5.s

# target to generate assembly for a file
simulation/gpu_implementation5.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/gpu_implementation5.cpp.s
.PHONY : simulation/gpu_implementation5.cpp.s

simulation/gpu_partition.o: simulation/gpu_partition.cpp.o
.PHONY : simulation/gpu_partition.o

# target to build an object file
simulation/gpu_partition.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/gpu_partition.cpp.o
.PHONY : simulation/gpu_partition.cpp.o

simulation/gpu_partition.i: simulation/gpu_partition.cpp.i
.PHONY : simulation/gpu_partition.i

# target to preprocess a source file
simulation/gpu_partition.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/gpu_partition.cpp.i
.PHONY : simulation/gpu_partition.cpp.i

simulation/gpu_partition.s: simulation/gpu_partition.cpp.s
.PHONY : simulation/gpu_partition.s

# target to generate assembly for a file
simulation/gpu_partition.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/gpu_partition.cpp.s
.PHONY : simulation/gpu_partition.cpp.s

simulation/hssoa/host_side_soa.o: simulation/hssoa/host_side_soa.cpp.o
.PHONY : simulation/hssoa/host_side_soa.o

# target to build an object file
simulation/hssoa/host_side_soa.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/hssoa/host_side_soa.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/simulation/hssoa/host_side_soa.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_sort.dir/build.make CMakeFiles/verify_sort.dir/simulation/hssoa/host_side_soa.cpp.o
.PHONY : simulation/hssoa/host_side_soa.cpp.o

simulation/hssoa/host_side_soa.i: simulation/hssoa/host_side_soa.cpp.i
.PHONY : simulation/hssoa/host_side_soa.i

# target to preprocess a source file
simulation/hssoa/host_side_soa.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/hssoa/host_side_soa.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/simulation/hssoa/host_side_soa.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_sort.dir/build.make CMakeFiles/verify_sort.dir/simulation/hssoa/host_side_soa.cpp.i
.PHONY : simulation/hssoa/host_side_soa.cpp.i

simulation/hssoa/host_side_soa.s: simulation/hssoa/host_side_soa.cpp.s
.PHONY : simulation/hssoa/host_side_soa.s

# target to generate assembly for a file
simulation/hssoa/host_side_soa.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/hssoa/host_side_soa.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/simulation/hssoa/host_side_soa.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_sort.dir/build.make CMakeFiles/verify_sort.dir/simulation/hssoa/host_side_soa.cpp.s
.PHONY : simulation/hssoa/host_side_soa.cpp.s

simulation/hssoa/proxypoint2d.o: simulation/hssoa/proxypoint2d.cpp.o
.PHONY : simulation/hssoa/proxypoint2d.o

# target to build an object file
simulation/hssoa/proxypoint2d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/hssoa/proxypoint2d.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/simulation/hssoa/proxypoint2d.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_sort.dir/build.make CMakeFiles/verify_sort.dir/simulation/hssoa/proxypoint2d.cpp.o
.PHONY : simulation/hssoa/proxypoint2d.cpp.o

simulation/hssoa/proxypoint2d.i: simulation/hssoa/proxypoint2d.cpp.i
.PHONY : simulation/hssoa/proxypoint2d.i

# target to preprocess a source file
simulation/hssoa/proxypoint2d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/hssoa/proxypoint2d.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/simulation/hssoa/proxypoint2d.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_sort.dir/build.make CMakeFiles/verify_sort.dir/simulation/hssoa/proxypoint2d.cpp.i
.PHONY : simulation/hssoa/proxypoint2d.cpp.i

simulation/hssoa/proxypoint2d.s: simulation/hssoa/proxypoint2d.cpp.s
.PHONY : simulation/hssoa/proxypoint2d.s

# target to generate assembly for a file
simulation/hssoa/proxypoint2d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/hssoa/proxypoint2d.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/simulation/hssoa/proxypoint2d.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_sort.dir/build.make CMakeFiles/verify_sort.dir/simulation/hssoa/proxypoint2d.cpp.s
.PHONY : simulation/hssoa/proxypoint2d.cpp.s

simulation/kernel_declarations.o: simulation/kernel_declarations.cuh.o
.PHONY : simulation/kernel_declarations.o

# target to build an object file
simulation/kernel_declarations.cuh.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/kernel_declarations.cuh.o
.PHONY : simulation/kernel_declarations.cuh.o

simulation/kernel_declarations.i: simulation/kernel_declarations.cuh.i
.PHONY : simulation/kernel_declarations.i

# target to preprocess a source file
simulation/kernel_declarations.cuh.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/kernel_declarations.cuh.i
.PHONY : simulation/kernel_declarations.cuh.i

simulation/kernel_declarations.s: simulation/kernel_declarations.cuh.s
.PHONY : simulation/kernel_declarations.s

# target to generate assembly for a file
simulation/kernel_declarations.cuh.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/kernel_declarations.cuh.s
.PHONY : simulation/kernel_declarations.cuh.s

simulation/kernels.o: simulation/kernels.cu.o
.PHONY : simulation/kernels.o

# target to build an object file
simulation/kernels.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/kernels.cu.o
.PHONY : simulation/kernels.cu.o

simulation/kernels.i: simulation/kernels.cu.i
.PHONY : simulation/kernels.i

# target to preprocess a source file
simulation/kernels.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/kernels.cu.i
.PHONY : simulation/kernels.cu.i

simulation/kernels.s: simulation/kernels.cu.s
.PHONY : simulation/kernels.s

# target to generate assembly for a file
simulation/kernels.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/kernels.cu.s
.PHONY : simulation/kernels.cu.s

simulation/model.o: simulation/model.cpp.o
.PHONY : simulation/model.o

# target to build an object file
simulation/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/model.cpp.o
.PHONY : simulation/model.cpp.o

simulation/model.i: simulation/model.cpp.i
.PHONY : simulation/model.i

# target to preprocess a source file
simulation/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/model.cpp.i
.PHONY : simulation/model.cpp.i

simulation/model.s: simulation/model.cpp.s
.PHONY : simulation/model.s

# target to generate assembly for a file
simulation/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/model.cpp.s
.PHONY : simulation/model.cpp.s

simulation/parameters_sim.o: simulation/parameters_sim.cpp.o
.PHONY : simulation/parameters_sim.o

# target to build an object file
simulation/parameters_sim.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/parameters_sim.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/simulation/parameters_sim.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_sort.dir/build.make CMakeFiles/verify_sort.dir/simulation/parameters_sim.cpp.o
.PHONY : simulation/parameters_sim.cpp.o

simulation/parameters_sim.i: simulation/parameters_sim.cpp.i
.PHONY : simulation/parameters_sim.i

# target to preprocess a source file
simulation/parameters_sim.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/parameters_sim.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/simulation/parameters_sim.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_sort.dir/build.make CMakeFiles/verify_sort.dir/simulation/parameters_sim.cpp.i
.PHONY : simulation/parameters_sim.cpp.i

simulation/parameters_sim.s: simulation/parameters_sim.cpp.s
.PHONY : simulation/parameters_sim.s

# target to generate assembly for a file
simulation/parameters_sim.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplate.dir/build.make CMakeFiles/cplate.dir/simulation/parameters_sim.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/preparer_cli.dir/build.make CMakeFiles/preparer_cli.dir/simulation/parameters_sim.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_sort.dir/build.make CMakeFiles/verify_sort.dir/simulation/parameters_sim.cpp.s
.PHONY : simulation/parameters_sim.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cplate"
	@echo "... preparer_cli"
	@echo "... verify_sort"
	@echo "... _utilities/main_verify_sort.o"
	@echo "... _utilities/main_verify_sort.i"
	@echo "... _utilities/main_verify_sort.s"
	@echo "... cli/main.o"
	@echo "... cli/main.i"
	@echo "... cli/main.s"
	@echo "... gui/colormap.o"
	@echo "... gui/colormap.i"
	@echo "... gui/colormap.s"
	@echo "... preparer/cli/cli_preparer_main.o"
	@echo "... preparer/cli/cli_preparer_main.i"
	@echo "... preparer/cli/cli_preparer_main.s"
	@echo "... preparer/data_preparer.o"
	@echo "... preparer/data_preparer.i"
	@echo "... preparer/data_preparer.s"
	@echo "... preparer/parameterparser.o"
	@echo "... preparer/parameterparser.i"
	@echo "... preparer/parameterparser.s"
	@echo "... simulation/data_manager/host_side_data.o"
	@echo "... simulation/data_manager/host_side_data.i"
	@echo "... simulation/data_manager/host_side_data.s"
	@echo "... simulation/data_manager/windandcurrentinterpolator.o"
	@echo "... simulation/data_manager/windandcurrentinterpolator.i"
	@echo "... simulation/data_manager/windandcurrentinterpolator.s"
	@echo "... simulation/gpu_implementation5.o"
	@echo "... simulation/gpu_implementation5.i"
	@echo "... simulation/gpu_implementation5.s"
	@echo "... simulation/gpu_partition.o"
	@echo "... simulation/gpu_partition.i"
	@echo "... simulation/gpu_partition.s"
	@echo "... simulation/hssoa/host_side_soa.o"
	@echo "... simulation/hssoa/host_side_soa.i"
	@echo "... simulation/hssoa/host_side_soa.s"
	@echo "... simulation/hssoa/proxypoint2d.o"
	@echo "... simulation/hssoa/proxypoint2d.i"
	@echo "... simulation/hssoa/proxypoint2d.s"
	@echo "... simulation/kernel_declarations.o"
	@echo "... simulation/kernel_declarations.i"
	@echo "... simulation/kernel_declarations.s"
	@echo "... simulation/kernels.o"
	@echo "... simulation/kernels.i"
	@echo "... simulation/kernels.s"
	@echo "... simulation/model.o"
	@echo "... simulation/model.i"
	@echo "... simulation/model.s"
	@echo "... simulation/parameters_sim.o"
	@echo "... simulation/parameters_sim.i"
	@echo "... simulation/parameters_sim.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

